name: firebase_remote_config_example
description: App fo demonstrate work with Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0

  firebase_core: ^1.24.0
  firebase_analytics: ^9.3.8
  firebase_remote_config: ^2.0.20

  shared_preferences: ^2.0.15

  permission_handler: ^10.1.0
  webview_flutter: ^3.0.4

  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flame_audio: ^1.3.2
  flutter_native_splash: ^2.2.13
  device_info: ^2.0.3
  flutter_sim_country_code: ^0.1.2
  onesignal_flutter: ^3.4.2
  flutter_launcher_icons: ^0.10.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/audio/applause.mp3
   - assets/audio/football-punt.mp3
   - assets/images/ball.png
   - assets/images/Player blu left leg.png
   - assets/images/Player Blu.png
   - assets/images/Player red left leg.png
   - assets/images/Player Red.png
   - assets/images/porta left.png
   - assets/images/porta right.png
   - assets/images/terreno.png
   - assets/images/back.png
   - assets/images/zero.png
   - assets/images/one.png
   - assets/images/two.png
   - assets/images/three.png
   - assets/images/four.png
   - assets/images/five.png
   - assets/images/six.png
   - assets/images/seven.png
   - assets/images/eight.png
   - assets/images/nine.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
