name: firebase_remote_config_example
description: App fo demonstrate work with Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0

  firebase_core: ^1.24.0
  firebase_analytics: ^9.3.8
  firebase_remote_config: ^2.0.20

  shared_preferences: ^2.0.15

  device_info_plus: ^6.0.0
  carrier_info: ^2.0.5
  permission_handler: ^10.1.0
  webview_flutter: ^3.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - asset/background.png
